# Generated by Django 4.2.6 on 2023-10-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolpost',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
